import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { descriptorToMetaTs } from "../dist/meta/descriptor-to-meta-ts.js";
import { irToDescriptor } from "../dist/meta/ir-to-descriptor.js";
import { buildSeedMetaIr } from "../dist/introspection/seed-meta.js";
import { runGenerateMetaTsCommand } from "../dist/commands/generate.js";
import {
  closeProjectSession,
  openProjectSession,
} from "../dist/session/project-session.js";
import { loadSetupCatalog, resolveSeed } from "../dist/catalog/setup-catalog.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixture = path.join(__dirname, "fixtures", "sample-project");
const cli = path.join(__dirname, "..", "dist", "cli.js");

async function withStateMachineSession(fn) {
  const catalog = loadSetupCatalog(fixture);
  const entry = resolveSeed(catalog, "StateMachine");
  const context = await openProjectSession({ cwd: fixture, seed: entry });
  try {
    await fn(context);
  } finally {
    await closeProjectSession();
  }
}

test("descriptorToMetaTs emits concept union and attribute types", () => {
  const source = descriptorToMetaTs(
    {
      version: 1,
      concepts: {
        State: {
          attributes: {
            isInitial: "bool",
            isFinal: "bool",
          },
          pointers: {
            entry: "Action",
          },
        },
        Action: {
          attributes: { body: "string" },
        },
        Constraint: {
          attributes: {
            kind: { type: "enum", values: ["safety", "goal"] },
          },
        },
        Machine: {
          contains: {
            State: "*",
            Action: "*",
          },
        },
        Event: {},
      },
    },
    { seedName: "Demo" },
  );

  assert.match(source, /Generated by webdot generate meta-ts/);
  assert.match(source, /Seed: Demo/);
  assert.match(source, /export type MetaConceptName =/);
  assert.match(source, /\| "Action"/);
  assert.match(source, /\| "State"/);
  assert.match(source, /export const MetaConcepts = \{/);
  assert.match(source, /export interface StateAttributes \{/);
  assert.match(source, /isInitial: boolean;/);
  assert.match(source, /export interface ConstraintAttributes \{/);
  assert.match(source, /kind: "safety" \| "goal";/);
  assert.match(source, /export interface StatePointers \{/);
  assert.match(source, /entry: "Action";/);
  assert.match(source, /export type MachineContains = \{/);
  assert.match(source, /State: "\*";/);
  assert.match(source, /Event: Record<string, never>;/);
  assert.match(source, /export type AttributesByConcept/);
  assert.match(source, /export type PointersByConcept/);
  assert.doesNotMatch(source, /export namespace/);
});

test("descriptorToMetaTs wraps in namespace when requested", () => {
  const source = descriptorToMetaTs(
    { version: 1, concepts: { A: {} } },
    { seedName: "X", namespace: "StaMS" },
  );
  assert.match(source, /export namespace StaMS \{/);
  assert.match(source, /export type MetaConceptName =/);
  assert.match(source, /^\}$/m);
});

test("descriptorToMetaTs rejects invalid concept identifiers", () => {
  assert.throws(
    () =>
      descriptorToMetaTs(
        { version: 1, concepts: { "bad-name": {} } },
        { seedName: "X" },
      ),
    /valid TypeScript identifier/,
  );
});

test("descriptorToMetaTs rejects invalid namespace", () => {
  assert.throws(
    () =>
      descriptorToMetaTs({ version: 1, concepts: { A: {} } }, { seedName: "X", namespace: "1bad" }),
    /valid TypeScript identifier/,
  );
});

test("descriptorToMetaTs handles multi-target pointers and set members", () => {
  const source = descriptorToMetaTs(
    {
      version: 1,
      concepts: {
        Flow: {
          pointers: { dst: ["In", "Out"] },
          sets: {
            members: { A: "+", B: "0..1" },
          },
        },
        In: {},
        Out: {},
        A: {},
        B: {},
      },
    },
    { seedName: "Multi" },
  );
  assert.match(source, /dst: "In" \| "Out";/);
  assert.match(source, /export interface FlowSets \{/);
  assert.match(source, /members: \{/);
  assert.match(source, /A: "\+";/);
});

test("descriptorToMetaTs matches StateMachine fixture meta", async () => {
  await withStateMachineSession(async (context) => {
    const ir = buildSeedMetaIr(context);
    const descriptor = irToDescriptor(ir, context);
    const source = descriptorToMetaTs(descriptor, { seedName: "StateMachine" });

    assert.match(source, /\| "Transition"/);
    assert.match(source, /export interface TransitionPointers \{/);
    assert.match(source, /src: "State";/);
    assert.match(source, /dst: "State";/);
    assert.match(source, /export type MachineContains/);
    assert.match(source, /Constraint: "\*";/);
    assert.match(source, /kind: "safety" \| "goal";/);
  });
});

test("runGenerateMetaTsCommand writes --out and returns source", async () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "webdot-meta-ts-"));
  const outRel = path.join("gen", "meta.ts");
  try {
    const result = await runGenerateMetaTsCommand({
      cwd: fixture,
      seed: "StateMachine",
      out: outRel,
    });
    assert.equal(result.seedName, "StateMachine");
    assert.ok(result.outFile);
    assert.equal(result.outFile, path.join(fixture, outRel));
    assert.equal(fs.readFileSync(result.outFile, "utf8"), result.source);
    assert.match(result.source, /MetaConceptName/);
  } finally {
    fs.rmSync(path.join(fixture, "gen"), { recursive: true, force: true });
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});

test("cli generate meta-ts prints to stdout", () => {
  const result = spawnSync(
    process.execPath,
    [cli, "generate", "meta-ts", "--seed", "StateMachine", "-C", fixture],
    { encoding: "utf8" },
  );
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /export type MetaConceptName/);
  assert.match(result.stdout, /TransitionPointers/);
});

test("cli generate meta-ts --out writes file and notes on stderr", () => {
  const outFile = path.join(fixture, "_generated_meta.ts");
  try {
    const result = spawnSync(
      process.execPath,
      [
        cli,
        "generate",
        "meta-ts",
        "--seed",
        "StateMachine",
        "-C",
        fixture,
        "--out",
        "_generated_meta.ts",
      ],
      { encoding: "utf8" },
    );
    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stderr, /wrote:/);
    assert.equal(result.stdout.trim(), "");
    assert.match(fs.readFileSync(outFile, "utf8"), /MetaConcepts/);
  } finally {
    fs.rmSync(outFile, { force: true });
  }
});

test("cli generate meta-ts without seed exits 2", () => {
  const result = spawnSync(process.execPath, [cli, "generate", "meta-ts"], {
    encoding: "utf8",
    cwd: os.tmpdir(),
  });
  assert.equal(result.status, 2);
  assert.match(result.stderr, /requires --seed/);
});
