import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import {
  closeProjectSession,
  openProjectSession,
} from "../dist/session/project-session.js";
import { loadSetupCatalog, resolveSeed } from "../dist/catalog/setup-catalog.js";

const require = createRequire(import.meta.url);
const { descriptorToMetaTs } = require("../plugins/GenerateMetaTs/lib/descriptor-to-meta-ts.js");
const { buildDescriptorFromCore } = require("../plugins/GenerateMetaTs/lib/build-descriptor.js");

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixture = path.join(__dirname, "fixtures", "sample-project");
const cli = path.join(__dirname, "..", "dist", "cli.js");
const repoRoot = path.join(__dirname, "..");
const pluginDirRel = path.join("plugins", "GenerateMetaTs");

async function withStateMachineSession(fn) {
  const catalog = loadSetupCatalog(fixture);
  const entry = resolveSeed(catalog, "StateMachine");
  const context = await openProjectSession({ cwd: fixture, seed: entry });
  try {
    await fn(context);
  } finally {
    await closeProjectSession();
  }
}

test("descriptorToMetaTs emits concept-centric Meta table", () => {
  const source = descriptorToMetaTs(
    {
      version: 1,
      concepts: {
        State: {
          attributes: {
            isInitial: "bool",
            isFinal: "bool",
          },
          pointers: {
            entry: "Action",
          },
        },
        Action: {
          attributes: { body: "string" },
        },
        Constraint: {
          attributes: {
            kind: { type: "enum", values: ["safety", "goal"] },
          },
        },
        Machine: {
          contains: {
            State: "*",
            Action: "*",
          },
        },
        Event: {},
      },
    },
    { seedName: "Demo" },
  );

  assert.match(source, /Generated by GenerateMetaTs/);
  assert.match(source, /Seed: Demo/);
  assert.match(source, /export const Meta = \{/);
  assert.match(source, /State: \{/);
  assert.match(source, /name: "State"/);
  assert.match(source, /isInitial: "bool"/);
  assert.match(source, /entry: "Action"/);
  assert.match(source, /kind: \{ type: "enum", values: \["safety", "goal"\] as const \}/);
  assert.match(source, /contains: \{"Action":"\*","State":"\*"\}/);
  assert.match(source, /export type MetaConcept = keyof typeof Meta/);
  assert.match(source, /export type AttrsOf</);
  assert.match(source, /export type PointersOf</);
  assert.doesNotMatch(source, /AttributesByConcept/);
  assert.doesNotMatch(source, /PointersByConcept/);
  assert.doesNotMatch(source, /ContainsByConcept/);
  assert.doesNotMatch(source, /SetsByConcept/);
  assert.doesNotMatch(source, /MetaConceptName/);
  assert.doesNotMatch(source, /export namespace/);
});

test("descriptorToMetaTs wraps in namespace when requested", () => {
  const source = descriptorToMetaTs(
    { version: 1, concepts: { A: {} } },
    { seedName: "X", namespace: "StaMS" },
  );
  assert.match(source, /export namespace StaMS \{/);
  assert.match(source, /export const Meta = \{/);
  assert.match(source, /^\}$/m);
});

test("descriptorToMetaTs rejects invalid concept identifiers", () => {
  assert.throws(
    () =>
      descriptorToMetaTs(
        { version: 1, concepts: { "bad-name": {} } },
        { seedName: "X" },
      ),
    /valid TypeScript identifier/,
  );
});

test("descriptorToMetaTs rejects invalid namespace", () => {
  assert.throws(
    () =>
      descriptorToMetaTs({ version: 1, concepts: { A: {} } }, { seedName: "X", namespace: "1bad" }),
    /valid TypeScript identifier/,
  );
});

test("descriptorToMetaTs handles multi-target pointers and set members", () => {
  const source = descriptorToMetaTs(
    {
      version: 1,
      concepts: {
        Flow: {
          pointers: { dst: ["In", "Out"] },
          sets: {
            members: { A: "+", B: "0..1" },
          },
        },
        In: {},
        Out: {},
        A: {},
        B: {},
      },
    },
    { seedName: "Multi" },
  );
  assert.match(source, /dst: \["In", "Out"\] as const/);
  assert.match(source, /Flow: \{/);
  assert.match(source, /members: \{"A":"\+","B":"0\.\.1"\}/);
});

test("buildDescriptorFromCore + descriptorToMetaTs match StateMachine fixture", async () => {
  await withStateMachineSession(async (context) => {
    const descriptor = buildDescriptorFromCore(context.core, context.rootNode);
    const source = descriptorToMetaTs(descriptor, { seedName: "StateMachine" });

    assert.match(source, /export const Meta = \{/);
    assert.match(source, /Transition: \{/);
    assert.match(source, /src: "State"/);
    assert.match(source, /dst: "State"/);
    assert.match(source, /Machine: \{/);
    assert.match(source, /"Constraint":"\*"/);
    assert.match(source, /kind: \{ type: "enum"/);
    assert.doesNotMatch(source, /AttributesByConcept/);
  });
});

test("cli plugin run GenerateMetaTs writes meta.ts via --artifacts-out", () => {
  const outDir = path.join(repoRoot, "_meta_ts_out");
  fs.rmSync(outDir, { recursive: true, force: true });
  try {
    const result = spawnSync(
      process.execPath,
      [
        cli,
        "plugin",
        "run",
        "--plugin-dir",
        pluginDirRel,
        "--seed",
        "StateMachine",
        "-C",
        fixture,
        "--set",
        "seedName=StateMachine",
        "--artifacts-out",
        "_meta_ts_out",
      ],
      { encoding: "utf8", cwd: repoRoot },
    );
    assert.equal(result.status, 0, result.stderr + "\n" + result.stdout);
    const metaPath = path.join(outDir, "meta.ts");
    assert.ok(fs.existsSync(metaPath), "expected meta.ts under shell-cwd artifacts-out");
    const source = fs.readFileSync(metaPath, "utf8");
    assert.match(source, /Generated by GenerateMetaTs/);
    assert.match(source, /export const Meta = \{/);
    assert.match(source, /Transition: \{/);
    assert.doesNotMatch(source, /AttributesByConcept/);
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});

test("cli plugin run GenerateMetaTs honors --set namespace and fileName", () => {
  const outDir = path.join(repoRoot, "_meta_ts_ns_out");
  fs.rmSync(outDir, { recursive: true, force: true });
  try {
    const result = spawnSync(
      process.execPath,
      [
        cli,
        "plugin",
        "run",
        "--plugin-dir",
        pluginDirRel,
        "--seed",
        "StateMachine",
        "-C",
        fixture,
        "--set",
        "namespace=StaMS",
        "--set",
        "fileName=types.ts",
        "--set",
        "seedName=StateMachine",
        "--artifacts-out",
        "_meta_ts_ns_out",
      ],
      { encoding: "utf8", cwd: repoRoot },
    );
    assert.equal(result.status, 0, result.stderr + "\n" + result.stdout);
    const metaPath = path.join(outDir, "types.ts");
    assert.ok(fs.existsSync(metaPath), "expected types.ts under shell-cwd artifacts-out");
    const source = fs.readFileSync(metaPath, "utf8");
    assert.match(source, /export namespace StaMS \{/);
    assert.match(source, /export const Meta = \{/);
    assert.match(source, /Seed: StateMachine/);
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});
